spring:
  application:
    name: sys-center

security:
  basic:
    enabled: true
  user:
    name: zcl
    password: zcl123

server:
    port: 8761 #启动端口

eureka:
  instance:
    hostname: sys-center        #Eureka实例的主机名
    prefer-ip-address: true
  client:
    registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
