spring:
  profiles:
    active: prod
  application:
    name: sys-gate
  redis:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    password:

server:
  port: 8050


zuul:
  routes:
    sys-admin:
      path: /sysAdmin/**
      service-id: sys-admin
    sys-auth:
      path: /sysAuth/**
      service-id: sys-auth
    cqjj-trade:
      path: /cqjjTrade/**
      service-id: cqjj-trade


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000


---
spring:
  profiles: dev
  redis:
    host: localhost

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


---
spring:
  profiles: prod
  redis:
    host: redis-server

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://zcl:zcl123@sys-center:8761/eureka/
