spring:
  application:
    name: sys-gate
server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/



zuul:
  routes:
    sys-admin:
      path: /sysAdmin/**
      service-id: sys-admin
    sys-auth:
      path: /sysAuth/**
      service-id: sys-auth



