spring:
  profiles:
    active: prod
  application:
    name: sys-admin
  redis:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    password: 
  datasource:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 600000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: "druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000"
    useGlobalDataSourceStat: true

server:
  port: 8001

mybatis:
  basepackage: cn.zoucl.cloud.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml



---
spring:
  profiles: dev
  redis:
    host: localhost
  datasource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cqjj?serverTimezone=UTC&noAccessToProcedureBodies=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
    username: root
    password: root

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


---
spring:
  profiles: prod
  redis:
    host: redis-server
  datasource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/cqjj?serverTimezone=UTC&noAccessToProcedureBodies=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
    username: root
    password: root

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://zcl:zcl123@sys-center:8761/eureka/