spring:
  application:
    name: sys-admin

eureka:
    instance:
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/


server:
  port: 8000