spring:
  profiles:
    active: dev
  application:
    name: cqjj-trade
  datasource:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 600000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: "druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000"
    useGlobalDataSourceStat: true

mybatis:
  basepackage: cn.zoucl.cloud.trade.mapper
  xmlLocation: classpath:mapper/**/*.xml

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/



---
spring:
  profiles: dev
  datasource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cqjj_hscs?serverTimezone=UTC&noAccessToProcedureBodies=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
    username: root
    password: root

server:
  port: 8002
